services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: blog
    container_name: django_blog
    restart: always
    command: /start
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - '8001:8000'
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    volumes:
      - db:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: always
    container_name: blog_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${db_DATABASE}
      - POSTGRES_USER=${db_USER}
      - POSTGRES_PASSWORD=${db_PASSWORD}
volumes:
  db: